include: package:lint/analysis_options.yaml

linter:
  rules:
    lines_longer_than_80_chars: false
    avoid_function_literals_in_foreach_calls: false
    avoid_bool_literals_in_conditional_expressions: false
    prefer_function_declarations_over_variables: false
    sort_pub_dependencies: false