
include: package:flutter_lints/flutter.yaml

linter:
  rules:
    avoid_print: false
    prefer_single_quotes: true 
    prefer_final_locals: true
    non_constant_identifier_names: false

analyzer:
  errors: 
    invalid_annotation_target: ignore