name: aussie
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  auto_size_text: ^2.1.0
  cached_network_image: ^2.3.2+1
  carousel_slider: ^2.3.1
  cupertino_icons: ^1.0.0
  data_connection_checker: ^0.3.4
  double_back_to_close_app: ^1.2.0
  equatable: ^1.2.5
  expand_widget: ^1.1.0
  firebase_core: ^0.5.2
  fl_chart: null
  flutter_bloc: ^6.1.0
  flutter_screenutil: ^3.2.0
  flutter_svg: ^0.19.0
  google_maps_flutter: ^1.0.5
  http: ^0.12.2
  infinite_scroll_pagination: ^2.2.1
  provider: ^4.3.2+2
  shared_preferences: ^0.5.12+4
  smooth_star_rating: ^1.1.1
  url_launcher: ^5.7.2
  weather_icons: ^2.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^1.10.4
  cloud_firestore: ^0.14.3

flutter:

  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/
    - assets/json/
  fonts:
    - family: BrandIcons
      fonts:
        - asset: fonts/BrandIcons.ttf
