name: aussie
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.10.0 <3.0.0"

dependency_overrides:
  intl: ^0.17.0-nullsafety.2

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_form_bloc:
    git:
      url: https://github.com/hashem78/form_bloc
      path: packages/flutter_form_bloc
  multi_image_picker:
    git:
      url: https://github.com/Sh1d0w/multi_image_picker
  auto_size_text: ^2.1.0
  build_runner: ^1.10.9
  cached_network_image: ^2.3.2+1
  carousel_slider: ^2.3.1
  cloud_firestore_web: ^0.2.1+2
  cupertino_icons: ^1.0.0
  data_connection_checker: ^0.3.4
  double_back_to_close_app: ^2.0.1
  equatable: ^1.2.5
  expand_widget: ^1.1.0
  firebase_auth: ^0.18.4+1
  firebase_core: ^0.5.2
  firebase_storage: ^5.2.0
  flutter_bloc: ^6.1.0
  flutter_screenutil: ^3.2.0
  flutter_svg: ^0.19.0

  google_maps_flutter: ^1.0.5
  http: ^0.12.2
  image_picker: ^0.6.7+15
  infinite_scroll_pagination: ^2.2.1
  json_serializable: ^3.5.1
  loading_animations: ^2.1.0
  page_transition: ^1.1.7+3
  paginate_firestore: ^0.2.2
  photo_view: ^0.10.3
  place_picker: ^0.9.17
  provider: ^4.3.2+2
  shared_preferences: ^0.5.12+4
  uuid: ^2.2.2
  weather_icons: ^2.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  cloud_firestore: ^0.14.3

  json_annotation: ^3.1.1
  lint: ^1.0.0

flutter:

  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/
    - assets/json/
