name: evento
description: An event management application.

publish_to: "none"

version: 2.1.0

environment:
  sdk: ">=2.15.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  animations: ^2.0.2
  cached_network_image: ^3.2.0
  cupertino_icons: ^1.0.4
  double_back_to_close_app: ^2.1.0
  firebase_auth: ^3.3.7
  firebase_core: ^1.12.0
  firebase_storage: ^10.2.7
  flutter_screenutil: ^5.3.1
  google_maps_flutter: ^2.1.1
  http: ^0.13.4
  image_cropper: ^1.5.0
  intl: ^0.17.0
  image_picker: ^0.8.4+9
  path_provider: ^2.0.9
  photo_view: ^0.13.0
  shared_preferences: ^2.0.13
  uuid: ^3.0.6
  cloud_firestore: ^3.1.8
  flutter_riverpod: ^1.0.3
  hooks_riverpod: ^1.0.3
  place_picker: ^0.9.20-nullsafety
  flutterfire_ui: ^0.3.5+1
  flutter_hooks: ^0.18.2+1
  form_field_validator: ^1.1.0

dev_dependencies:
  freezed: ^1.1.1
  freezed_annotation: ^1.1.0
  build_runner: ^2.1.7
  json_annotation: ^4.4.0
  json_serializable: ^6.1.4
  flutter_lints: ^1.0.4

flutter:
  uses-material-design: true
  assets:
    - assets/json/
