name: aussie
description: A new Flutter project.

publish_to: 'none'

version: 2.0.0

environment:
  sdk: '>=2.12.0 <3.0.0'
  

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  place_picker: ^0.9.19-nullsafety
  flutter_form_bloc: ^0.20.4
  multi_image_picker2: ^5.0.2
  animations: ^2.0.0
  auto_size_text: ^3.0.0-nullsafety.0
  cached_network_image: ^3.0.0
  carousel_slider: ^4.0.0
  cupertino_icons: ^1.0.3
  intl: ^0.17.0
  
  double_back_to_close_app: ^2.0.1
  equatable: ^2.0.3
  expand_widget: ^2.1.0
  firebase_auth: ^1.4.1
  firebase_core: ^1.3.0
  firebase_storage: ^8.1.3
  flutter_bloc: ^7.0.1
  flutter_screenutil: ^5.0.0+2
  flutter_svg: ^0.22.0
  google_maps_flutter: ^2.0.6
  http: ^0.13.3
  image_cropper: ^1.4.1
  infinite_scroll_pagination: ^3.0.1+1
  path_provider: ^2.0.2
  photo_view: ^0.11.1
  provider: ^5.0.0
  shared_preferences: ^2.0.6
  uuid: ^3.0.4
  weather_icons: ^3.0.0-nullsafety.0

dev_dependencies:
  
  build_runner: ^2.0.5
  cloud_firestore: ^2.2.2
  json_annotation: ^4.0.1
  json_serializable: ^4.1.3
  lint: ^1.5.3

flutter:

  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/
    - assets/json/
