name: aussie
description: A new Flutter project.

publish_to: 'none'

version: 2.1.0

environment:
  sdk: '>=2.15.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  animations: ^2.0.2
  auto_size_text: ^3.0.0
  cached_network_image: ^3.2.0
  cupertino_icons: ^1.0.3
  double_back_to_close_app: ^2.1.0
  equatable: ^2.0.3
  expand_widget: ^2.1.0
  firebase_auth: ^3.3.7 
  firebase_core: ^1.12.0 
  firebase_storage: ^10.2.7
  flutter_bloc: ^8.0.1
  flutter_form_bloc: ^0.29.3
  flutter_screenutil: ^5.3.0
  google_maps_flutter: ^2.1.1
  http: ^0.13.4
  image_cropper: ^1.4.1
  intl: ^0.17.0
  multi_image_picker2: ^5.0.2
  path_provider: ^2.0.9
  photo_view: ^0.13.0
  shared_preferences: ^2.0.13
  uuid: ^3.0.5
  cloud_firestore: ^3.1.8
  flutter_riverpod: ^1.0.3
  hooks_riverpod: ^1.0.3
  freezed: ^1.1.1
  freezed_annotation: ^1.1.0
  infinite_scroll_pagination: ^3.1.0
  place_picker: ^0.9.20-nullsafety
  flutterfire_ui: ^0.3.4
  flutter_hooks: ^0.18.2+1

dev_dependencies:
  build_runner: ^2.1.7
  json_annotation: ^4.4.0
  json_serializable: ^6.1.4
  flutter_lints: ^1.0.4

flutter:

  uses-material-design: true
  assets:
    - assets/json/
